### ISSUE TITLE
Load .coffeelintrc by default

### ISSUE THREAD

**Issue by apennebaker** [clutchski/coffeelint#145]
Linters have a convention of a directory-local configuration file, so that they don't need to type `<linter> -f <configuration file>` each time. Thus, JSHint automatically loads any `.jshintrc` files it encounters in the directories applicable.

coffeelint should automatically load a configuration file, when present, such as `.coffeelintrc`,  `coffeelint.json`, or the like.

**Comment by markogresak** [comment]
Setting `COFFEELINT_CONFIG` doesn't work for me.

I have set

    export COFFEELINT_CONFIG=~/.coffeelintrc

and if I try `echo $COFFEELINT_CONFIG`, it's displayed correctly, but coffeelint doesn't detect global config, unless it's saved as `~/coffeelint.json`. Am I doing something wrong here or was this changed, because I believe it used to work some time ago.

**Comment by brunowego** [comment]
+1
