### ISSUE TITLE
Rule for calling function with arguments as first argument of other function

### ISSUE THREAD

**Issue by kibin** [clutchski/coffeelint#202]
I think there should be option in linter to flag code like this:

    @myAwesomeFunc1 @myAwesomeFunc2 argument, anotherArgument

Now it's not clear if `anotherArgument` is argument for `@myAwesomeFunc2` or is it just forgotten parens and it really was argument for `@myAwesomeFunc1` and code should be:

    @myAwesomeFunc1 (@myAwesomeFunc2 argument), anotherArgument

**Comment by swang** [comment]
Sorry you waited almost 2 years to hear this (even assuming you're still using CoffeeScript) but I'm going to say, "no" on this. You don't take out parens/braces in CoffeeScript because you can, you do it because removing them would not make the statement ambiguous. I am sure there could be a rule made that could catch this, but then I'd hear requests about adding flags or the support issues or some hidden CoffeeScript lexer gotcha which will make me regret implementing this.

**Comment by kibin** [comment]
No problem, I’m not using it anymore
