### ISSUE TITLE
Do not apply operator spacing rule to text in comments

### ISSUE THREAD

**Issue by ninjatronic** [clutchski/coffeelint#371]
I've noticed this because a common pattern when writing Ember components is to put an example of handlebars usage in a comment at the top...

```coffeescript
`import Ember from 'ember'`

# coffeelint: disable=space_operators
# operator spacing not relevant when demonstrating handlebars in a comment

#
# Usage:
# {{data-map
#   dataUrl=<String> The data URL
#   scope=<String> The scope of the map
#
#   projection=<String> The name of the projection to use
#   projectionCenter=<Array> The center of the projection
#   projectionRotation=<Array> The rotation of the projection
#   projectionParallels=<Array> The projection parallels
#   projectionScale=<Array> The scale of the projection
#
#     NB the projection translation is set automatically
#
#   regions=<Array> An array of Region objects.
#     A region should have...
#       region <String> : region code (eg USA, RUS) #todo this should become 'id'
#       temperature <Number> (Optional): integer indicating temperature
#
#   selectedRegion=<Object> The currently selected region #todo this only works from inside the map
# }}


# coffeelint: enable=space_operators

DataMapComponent = Ember.Component.extend

...
```
> example from [here](https://github.com/ninjatronic/vapr/blob/0f65aa69b2173038777a29d3eed77333faec55d7/app/components/data-map.coffee).

Either not applying the rule in comments, or specifying a flag to disable the rule during comments, would be super useful.

Thanks

**Comment by AsaAyers** [comment]
I can't reproduce the error. Since you linked to the source I even downloaded your file and your coffeelint.json and removed your disable/enable comments, still can't reproduce the error. You do get a couple errors in that comment because of lines being too long.

I also took a look at [the source for space_operators](https://github.com/clutchski/coffeelint/blob/master/src/rules/space_operators.coffee#L17) and it uses the [`LexicalLinter`](https://github.com/clutchski/coffeelint/blob/master/src/lexical_linter.coffee) which actually can't see that style of comment.
