### ISSUE TITLE
import is reserved word

### ISSUE THREAD

**Issue by erichonkanen** [clutchski/coffeelint#536]
Hello, I am trying out coffeelint with my ember-cli project and have an error being thrown for the es6 import in my files... How can I have coffeelint ignore this?

[image](https://cloud.githubusercontent.com/assets/230757/11376576/6a273182-9296-11e5-8a9b-3e054cd46cda.png)

```
import Ember from 'ember'
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin'

SettingsRoute = Ember.Route.extend AuthenticatedRouteMixin,
  beforeModel: (transition)->
    # If the user is not authenticated, send them to the homepage.
    if not @session.isAuthenticated
      @transitionTo 'index'
    ...
```

**Comment by AsaAyers** [comment]
CoffeeScript doesn't support ES6 modules, so what have there is a syntax error.

If CoffeeScript won't parse it there's no way CoffeeLint is going to lint it. If somehow your code does compile because you're using some fork of CoffeeScript you can try https://github.com/clutchski/coffeelint/blob/master/doc/user.md#what-about-different-flavors-of-coffeescript-like-icedcoffeescript

**Comment by ChrisOelmueller** [comment]
Just checking in here now that CoffeeScript does in fact support ES6 modules for about a year. What steps would I need to take in order to convince my linter it's all gonna be okay? ;-)

@AsaAyers  
I'd be grateful for pointers regarding proper syntax support, or silencing this very specific check. Easiest solution probably involves telling Coffeelint about the CS version I'd prefer it to use?

**Comment by AsaAyers** [comment]
@swang runs this project now.

My sincere suggestion is to use http://decaffeinate-project.org/ to move any project you have to JavaScript, and then replace CoffeeScript with https://babeljs.io/, and replace CoffeeLint with https://eslint.org/. There just aren't many benefits to using CoffeeScript vs JavaScript with Babel. See [You don't need CoffeeScript](https://gist.github.com/AsaAyers/d09e4de118b8d6b5e2d8fa3e38e496e0) for more details.

If you install CoffeeLint and CoffeeScript locally (`npm install --save-dev coffeelint coffee-script`), then CoffeeLint will use that local CoffeeScript.
