### ISSUE TITLE
Why 'Operators must be spaced properly  &&'?

### ISSUE THREAD

**Issue by kongakong** [clutchski/coffeelint#547]
Here is the coffeescript code. The line that causes the exception is marked with `## <- Error` at the end.

```
SAFETY_EXPANDER_TIMEOUT = 300#ms
...

      startExpandingAt = _.now()

      while @_someCondition()\
      and _.now() - startExpandingAt < SAFETY_EXPANDER_TIMEOUT  ## <- Error
```

Why it causes the exception `'Operators must be spaced properly  &&`? How can I fix it? I am using version 1.14.2

**Comment by AsaAyers** [comment]
This is the first example I've seen in coffeescript of using `\` for a line continuation and putting the `and` on the next line. If you move your `and` to the previous line you won't need the `\` for line continuation and it will fix this error.

```
while @_someCondition() and
_.now() - startExpandingAt < SAFETY_EXPANDER_TIMEOUT  ## <- Error
```

I'm not closing the issue because this still seems like a bug that could be addressed.

**Comment by swang** [comment]
Hmm I would have to say this is not an error. The backslash is right next to the right paren so it sucks up the next available tokens (`and`) right next to it so the lexer (and therefore linter) sees it as

```coffeescript
while @_someCondition()and _.now()...
```
